apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: hello-world
    purpose: content
  name: cl-content-367
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: cl-content-367
spec:
  ports:
  - port: 4001
    protocol: TCP
    targetPort: 4001
  selector:
    app: hello-world
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world-deployment
  namespace: cl-content-367
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - env:
        - name: PORT
          value: "4001"
        image: quay.io/cdoan0/hello-world:latest
        imagePullPolicy: Always
        name: hello-world
        ports:
        - containerPort: 4001
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 32Mi
